# Generated by Django 2.0.4 on 2018-04-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_post_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='important',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
