# Generated by Django 2.0.4 on 2018-04-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_post_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='important',
            new_name='importance',
        ),
    ]
